pr:
  sao-jose-dos-pinhais:
    - "tres-marias"
    - "centro"
    - "aristocrata"
    - "bom-jesus"
    - "pedro-moro"
    - "ouro-fino"
    - "sao-pedro"
    - "sao-domingos"
    - "silveira-da-motta"
    - "braga"
  curitiba:
    - "jardim-das-americas"
    - "capao-da-imbuia"
    - "uberaba"
    - "batel"
    - "agua-verde"
    - "portao"
    - "cabral"
    - "cristo-rei"
    - "jardim-botanico"
    - "centro"
    - "reboucas"
